/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package foodordeingsystem;

/**
 *
 * @author qiqi0
 */
public class AddFood extends javax.swing.JFrame {

    /**
     * Creates new form AddFood1
     */
    public AddFood() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FoodTypeBG = new javax.swing.ButtonGroup();
        AddFoodL = new javax.swing.JLabel();
        IDL = new javax.swing.JLabel();
        SnackRB = new javax.swing.JRadioButton();
        MealRB = new javax.swing.JRadioButton();
        BeverageRB = new javax.swing.JRadioButton();
        IDTF = new javax.swing.JTextField();
        NameL = new javax.swing.JLabel();
        NameTF = new javax.swing.JTextField();
        PriceL = new javax.swing.JLabel();
        PriceTF = new javax.swing.JTextField();
        AddFoodB = new javax.swing.JButton();
        GoBackB = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Add Food");
        setPreferredSize(new java.awt.Dimension(600, 400));
        setResizable(false);
        getContentPane().setLayout(null);

        AddFoodL.setText("Add Food");
        getContentPane().add(AddFoodL);
        AddFoodL.setBounds(150, 20, 90, 16);

        IDL.setText("ID:");
        getContentPane().add(IDL);
        IDL.setBounds(50, 100, 90, 10);

        FoodTypeBG.add(SnackRB);
        SnackRB.setText("Snack");
        getContentPane().add(SnackRB);
        SnackRB.setBounds(250, 50, 110, 21);

        FoodTypeBG.add(MealRB);
        MealRB.setText("Meal");
        getContentPane().add(MealRB);
        MealRB.setBounds(30, 50, 90, 21);

        FoodTypeBG.add(BeverageRB);
        BeverageRB.setText("Beverage");
        getContentPane().add(BeverageRB);
        BeverageRB.setBounds(130, 50, 120, 21);

        IDTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDTFActionPerformed(evt);
            }
        });
        getContentPane().add(IDTF);
        IDTF.setBounds(130, 90, 110, 22);

        NameL.setText("Name:");
        getContentPane().add(NameL);
        NameL.setBounds(50, 140, 90, 10);
        getContentPane().add(NameTF);
        NameTF.setBounds(130, 130, 110, 22);

        PriceL.setText("Price (RM):");
        getContentPane().add(PriceL);
        PriceL.setBounds(50, 180, 80, 10);
        getContentPane().add(PriceTF);
        PriceTF.setBounds(130, 170, 110, 22);

        AddFoodB.setText("Add Food");
        AddFoodB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddFoodBActionPerformed(evt);
            }
        });
        getContentPane().add(AddFoodB);
        AddFoodB.setBounds(190, 220, 130, 23);

        GoBackB.setText("Go Back");
        GoBackB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GoBackBActionPerformed(evt);
            }
        });
        getContentPane().add(GoBackB);
        GoBackB.setBounds(50, 220, 110, 20);

        pack();
    }// </editor-fold>//GEN-END:initComponents
// Add Food
    private void AddFoodBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddFoodBActionPerformed
        String id = IDTF.getText();
        String itemName = NameTF.getText();
        String price = PriceTF.getText();
        double itemPrice = Double.parseDouble(price);

        
        String selectedFoodType = "";

        if (SnackRB.isSelected()) {
            selectedFoodType = SnackRB.getText();
        } else if (MealRB.isSelected()) {
            selectedFoodType = MealRB.getText();
        } else if (BeverageRB.isSelected()) {
            selectedFoodType = BeverageRB.getText();
        }

        System.out.println("Selected Food Type: " + selectedFoodType);
        System.out.println("ID: " + id);
        System.out.println("Item Name: " + itemName);
        System.out.println("Price: " + itemPrice);
        
        // Polymorphism
        if(selectedFoodType == "Meal"){
            Food food = new Meal(id, itemName, itemPrice, selectedFoodType);
             DB.addFood(food,selectedFoodType);
             
        }else if(selectedFoodType == "Snack"){
            Food food = new Snack(id, itemName, itemPrice, selectedFoodType);
             DB.addFood(food,selectedFoodType);
             
        }else if(selectedFoodType == "Beverage"){
            Food food = new Snack(id, itemName, itemPrice, selectedFoodType);
             DB.addFood(food,selectedFoodType);
             
        }
        
        
        
        
        

       
    }//GEN-LAST:event_AddFoodBActionPerformed

    private void IDTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IDTFActionPerformed
// Go Back to Management Menu
    private void GoBackBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GoBackBActionPerformed
        dispose();
        ManagementMenu managementPage = new ManagementMenu();

        managementPage.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_GoBackBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddFood.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddFood.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddFood.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddFood.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddFood().setVisible(true);
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddFoodB;
    private javax.swing.JLabel AddFoodL;
    private javax.swing.JRadioButton BeverageRB;
    private javax.swing.ButtonGroup FoodTypeBG;
    private javax.swing.JButton GoBackB;
    private javax.swing.JLabel IDL;
    private javax.swing.JTextField IDTF;
    private javax.swing.JRadioButton MealRB;
    private javax.swing.JLabel NameL;
    private javax.swing.JTextField NameTF;
    private javax.swing.JLabel PriceL;
    private javax.swing.JTextField PriceTF;
    private javax.swing.JRadioButton SnackRB;
    // End of variables declaration//GEN-END:variables
}
