/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package foodordeingsystem;

import javax.swing.JOptionPane;

/**
 *
 * @author qiqi0
 */
public class Login extends javax.swing.JFrame {

    private String username;

    public String getUsername() {
        return username;
    }

    /**
     * Creates new form MainMenu
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TitleL = new javax.swing.JLabel();
        LoginB = new javax.swing.JToggleButton();
        RegisterB = new javax.swing.JToggleButton();
        UsernameTF = new javax.swing.JTextField();
        UsernameL = new javax.swing.JLabel();
        PasswordTF = new javax.swing.JTextField();
        PaddwordL = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Main Menu");
        setPreferredSize(new java.awt.Dimension(600, 400));
        setResizable(false);
        getContentPane().setLayout(null);

        TitleL.setText("SUC Food Ordering System");
        getContentPane().add(TitleL);
        TitleL.setBounds(210, 20, 160, 40);

        LoginB.setText("Login");
        LoginB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginBActionPerformed(evt);
            }
        });
        getContentPane().add(LoginB);
        LoginB.setBounds(210, 170, 111, 23);

        RegisterB.setText("Register");
        RegisterB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterBActionPerformed(evt);
            }
        });
        getContentPane().add(RegisterB);
        RegisterB.setBounds(210, 210, 111, 23);

        UsernameTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsernameTFActionPerformed(evt);
            }
        });
        getContentPane().add(UsernameTF);
        UsernameTF.setBounds(230, 90, 120, 20);

        UsernameL.setText("Username:");
        getContentPane().add(UsernameL);
        UsernameL.setBounds(120, 90, 100, 16);

        PasswordTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordTFActionPerformed(evt);
            }
        });
        getContentPane().add(PasswordTF);
        PasswordTF.setBounds(230, 120, 120, 20);

        PaddwordL.setText("Password:");
        getContentPane().add(PaddwordL);
        PaddwordL.setBounds(120, 120, 100, 16);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RegisterBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterBActionPerformed
        dispose();
        Register menuPage = new Register();
        menuPage.setVisible(true);
    }//GEN-LAST:event_RegisterBActionPerformed

    private void UsernameTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsernameTFActionPerformed


    }//GEN-LAST:event_UsernameTFActionPerformed

    private void PasswordTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordTFActionPerformed
// perform Login 
    private void LoginBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginBActionPerformed
        username = UsernameTF.getText();
        String password = PasswordTF.getText();
        String role = DB.getRoleByUsername(username);
        System.out.println(role);

        if (DB.AuthLogin(username, password)) {
            JOptionPane.showMessageDialog(null, "Login successful!");
            if ("customer".equals(role)) {
                dispose();
                CustomerMenu foodMenu = new CustomerMenu();
                foodMenu.setVisible(true);

            } else if ("management".equals(role)) {
                dispose();
                ManagementMenu managementPage = new ManagementMenu();
                managementPage.setVisible(true);

            } else {
                System.out.println("error");
            }

        } else {
            JOptionPane.showMessageDialog(null, "Login failed!");
        }


    }//GEN-LAST:event_LoginBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }

        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton LoginB;
    private javax.swing.JLabel PaddwordL;
    private javax.swing.JTextField PasswordTF;
    private javax.swing.JToggleButton RegisterB;
    private javax.swing.JLabel TitleL;
    private javax.swing.JLabel UsernameL;
    private javax.swing.JTextField UsernameTF;
    // End of variables declaration//GEN-END:variables
}
