/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package foodordeingsystem;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.*;
import javax.swing.JOptionPane;

public class Register extends javax.swing.JFrame implements CreateAccount {

    /**
     * Creates new form Menu
     */
    public Register() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        UsernameL = new javax.swing.JLabel();
        UsernameTF = new javax.swing.JTextField();
        RegisterL = new javax.swing.JLabel();
        PasswordL = new javax.swing.JLabel();
        PasswordTF = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        RoleCB = new javax.swing.JComboBox<>();
        RegisterB = new javax.swing.JButton();
        GoBackB = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu");
        setPreferredSize(new java.awt.Dimension(600, 400));
        setResizable(false);
        getContentPane().setLayout(null);

        UsernameL.setText("Username:");
        getContentPane().add(UsernameL);
        UsernameL.setBounds(70, 70, 110, 16);

        UsernameTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsernameTFActionPerformed(evt);
            }
        });
        getContentPane().add(UsernameTF);
        UsernameTF.setBounds(170, 70, 110, 22);

        RegisterL.setText("Register");
        getContentPane().add(RegisterL);
        RegisterL.setBounds(180, 20, 60, 16);

        PasswordL.setText("Password:");
        getContentPane().add(PasswordL);
        PasswordL.setBounds(70, 110, 110, 16);

        PasswordTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordTFActionPerformed(evt);
            }
        });
        getContentPane().add(PasswordTF);
        PasswordTF.setBounds(170, 110, 110, 22);

        jLabel4.setText("Role:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(70, 150, 110, 16);

        RoleCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "customer", "management" }));
        RoleCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RoleCBActionPerformed(evt);
            }
        });
        getContentPane().add(RoleCB);
        RoleCB.setBounds(170, 150, 104, 22);

        RegisterB.setText("Register");
        RegisterB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterBActionPerformed(evt);
            }
        });
        getContentPane().add(RegisterB);
        RegisterB.setBounds(80, 210, 110, 23);

        GoBackB.setText("Go Back");
        GoBackB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GoBackBActionPerformed(evt);
            }
        });
        getContentPane().add(GoBackB);
        GoBackB.setBounds(215, 210, 100, 23);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UsernameTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsernameTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UsernameTFActionPerformed

    private void PasswordTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordTFActionPerformed

    private void RegisterBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterBActionPerformed
        dispose();
        CreateAccount();

//          
//       
// TODO add your handling code here:
    }//GEN-LAST:event_RegisterBActionPerformed

    private void RoleCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RoleCBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RoleCBActionPerformed

    private void GoBackBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GoBackBActionPerformed
        dispose();
        Login loginPage = new Login();
        loginPage.setVisible(true);
    }//GEN-LAST:event_GoBackBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton GoBackB;
    private javax.swing.JLabel PasswordL;
    private javax.swing.JTextField PasswordTF;
    private javax.swing.JButton RegisterB;
    private javax.swing.JLabel RegisterL;
    private javax.swing.JComboBox<String> RoleCB;
    private javax.swing.JLabel UsernameL;
    private javax.swing.JTextField UsernameTF;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables

    //interface implemented
    @Override
    public void CreateAccount() {
        String username = UsernameTF.getText();
        String password = PasswordTF.getText();
        String selectedValue = (String) RoleCB.getSelectedItem();

        if (selectedValue == "customer") {
            User newUser = new Customer(selectedValue, username, password);
            DB.register(newUser);
        } else if (selectedValue == "management") {
            User newUser = new Management(selectedValue, username, password);
            DB.register(newUser);
        }

    }
}
